using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.Networking;
using UnityEngine.Rendering;

public class AIAssistantWindow : EditorWindow
{
    const string Prefix = "UniversalCodingAgent.";
    const string DefaultSystem = "You are a senior Unity coding agent. Help write and debug C#, HLSL/ShaderLab, URP and editor tools. Give concrete code and explain file paths, assumptions and verification steps. Never claim to have modified files; return patches or complete snippets for the user to apply.";
    static string Provider { get => EditorPrefs.GetString(Prefix+"Provider", "DeepSeek"); set => EditorPrefs.SetString(Prefix+"Provider", value); }
    static string Endpoint { get => EditorPrefs.GetString(Prefix+"Endpoint", "https://api.deepseek.com/chat/completions"); set => EditorPrefs.SetString(Prefix+"Endpoint", value); }
    static string Model { get => EditorPrefs.GetString(Prefix+"Model", "deepseek-chat"); set => EditorPrefs.SetString(Prefix+"Model", value); }
    static string ApiKey { get => EditorPrefs.GetString(Prefix+"Key", ""); set => EditorPrefs.SetString(Prefix+"Key", value); }
    static string SystemPrompt { get => EditorPrefs.GetString(Prefix+"System", DefaultSystem); set => EditorPrefs.SetString(Prefix+"System", value); }
    static bool IncludeScene { get => EditorPrefs.GetBool(Prefix+"Scene", true); set => EditorPrefs.SetBool(Prefix+"Scene", value); }
    static bool IncludeSelection { get => EditorPrefs.GetBool(Prefix+"Selection", true); set => EditorPrefs.SetBool(Prefix+"Selection", value); }
    static bool IncludeLogs { get => EditorPrefs.GetBool(Prefix+"Logs", true); set => EditorPrefs.SetBool(Prefix+"Logs", value); }
    static string AttachedFile { get => EditorPrefs.GetString(Prefix+"File", ""); set => EditorPrefs.SetString(Prefix+"File", value); }

    [Serializable] class Msg { public string role; public string content; }
    [Serializable] class Req { public string model; public Msg[] messages; public float temperature = 0.2f; public bool stream = false; }
    [Serializable] class ChoiceMsg { public string content; }
    [Serializable] class Choice { public ChoiceMsg message; }
    [Serializable] class Resp { public Choice[] choices; }
    [Serializable] class ErrorBody { public ErrorInfo error; }
    [Serializable] class ErrorInfo { public string message; }
    class LogItem { public string type, text; }

    readonly List<Msg> history = new List<Msg>();
    readonly List<LogItem> logs = new List<LogItem>();
    string input = "", status = ""; bool settings, sending; Vector2 scroll; UnityWebRequest request;

    [MenuItem("Tools/Universal Coding Agent", false, 90)]
    static void Open() { var w = GetWindow<AIAssistantWindow>("Coding Agent"); w.minSize = new Vector2(520, 480); }
    void OnEnable() { Application.logMessageReceived += CaptureLog; EditorApplication.update += UpdateRequest; }
    void OnDisable() { Application.logMessageReceived -= CaptureLog; EditorApplication.update -= UpdateRequest; if (request != null) request.Dispose(); }
    void CaptureLog(string condition, string stack, LogType type) { if (type != LogType.Error && type != LogType.Exception && type != LogType.Warning) return; var line = condition.Split('\n')[0].Trim(); if (logs.Any(x => x.text == line)) return; logs.Add(new LogItem { type = type.ToString(), text = line }); if (logs.Count > 80) logs.RemoveAt(0); Repaint(); }

    void OnGUI() { Toolbar(); if (settings) Settings(); scroll = EditorGUILayout.BeginScrollView(scroll); foreach (var m in history) Bubble(m); if (sending) EditorGUILayout.LabelField("Waiting for model...", EditorStyles.miniLabel); EditorGUILayout.EndScrollView(); InputPanel(); if (!string.IsNullOrEmpty(status)) EditorGUILayout.HelpBox(status, MessageType.Info); }
    void Toolbar() { using (new EditorGUILayout.HorizontalScope(EditorStyles.toolbar)) { settings = GUILayout.Toggle(settings, "Settings", EditorStyles.toolbarButton, GUILayout.Width(65)); GUILayout.Label(Provider + " / " + Model, EditorStyles.miniLabel); GUILayout.FlexibleSpace(); if (GUILayout.Button("Clear", EditorStyles.toolbarButton, GUILayout.Width(50))) history.Clear(); if (GUILayout.Button("Attach file", EditorStyles.toolbarButton, GUILayout.Width(75))) PickFile(); if (GUILayout.Button("Copy prompt", EditorStyles.toolbarButton, GUILayout.Width(82))) CopyPrompt(); if (GUILayout.Button("Grab errors", EditorStyles.toolbarButton, GUILayout.Width(75))) GrabLog(); } }
    void Settings() { using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox)) { var names = new[] { "OpenAI / Codex", "Anthropic Claude", "DeepSeek", "GLM", "Google Gemini", "Qwen / DashScope", "Ollama", "Custom" }; int idx = Mathf.Max(0, Array.IndexOf(names, Provider)); int next = EditorGUILayout.Popup("Provider", idx, names); if (next != idx) { Provider = names[next]; ApplyPreset(Provider); } Endpoint = EditorGUILayout.TextField("Chat endpoint", Endpoint); var models = ModelsFor(Provider); int mi = Mathf.Max(0, Array.IndexOf(models, Model)); int mn = EditorGUILayout.Popup("Model", mi, models); if (mn != mi && mn < models.Length) Model = models[mn]; if (Provider == "Custom") Model = EditorGUILayout.TextField("Custom model", Model); ApiKey = EditorGUILayout.PasswordField("API key", ApiKey); if (GUILayout.Button("Detect endpoint compatibility")) DetectEndpoint(); SystemPrompt = EditorGUILayout.TextArea(SystemPrompt, GUILayout.Height(55)); IncludeScene = EditorGUILayout.ToggleLeft("Include active scene and render pipeline", IncludeScene); IncludeSelection = EditorGUILayout.ToggleLeft("Include selected objects and materials", IncludeSelection); IncludeLogs = EditorGUILayout.ToggleLeft("Include recent Console errors", IncludeLogs); if (!string.IsNullOrEmpty(AttachedFile)) EditorGUILayout.LabelField("Attached", AttachedFile); EditorGUILayout.LabelField("Keys are stored locally in Unity EditorPrefs.", EditorStyles.miniLabel); } }
    static string[] ModelsFor(string p) { if (p == "OpenAI / Codex") return new[] { "gpt-4.1", "gpt-4.1-mini", "gpt-4o", "o3-mini" }; if (p == "Anthropic Claude") return new[] { "claude-sonnet-4-20250514", "claude-3-7-sonnet-latest", "claude-3-5-haiku-latest" }; if (p == "DeepSeek") return new[] { "deepseek-chat", "deepseek-reasoner" }; if (p == "GLM") return new[] { "glm-4-plus", "glm-4-flash", "glm-4-air" }; if (p == "Google Gemini") return new[] { "gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.0-flash" }; if (p == "Qwen / DashScope") return new[] { "qwen-plus", "qwen-max", "qwen-turbo" }; if (p == "Ollama") return new[] { "qwen2.5-coder:7b", "deepseek-coder-v2:16b", "llama3.1:8b" }; return new[] { Model }; }
    static void ApplyPreset(string p) { if (p == "OpenAI / Codex") { Endpoint = "https://api.openai.com/v1/chat/completions"; Model = "gpt-4.1-mini"; } else if (p == "Anthropic Claude") { Endpoint = "https://api.anthropic.com/v1/messages"; Model = "claude-sonnet-4-20250514"; } else if (p == "DeepSeek") { Endpoint = "https://api.deepseek.com/chat/completions"; Model = "deepseek-chat"; } else if (p == "GLM") { Endpoint = "https://open.bigmodel.cn/api/paas/v4/chat/completions"; Model = "glm-4-flash"; } else if (p == "Google Gemini") { Endpoint = "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions"; Model = "gemini-2.5-flash"; } else if (p == "Qwen / DashScope") { Endpoint = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions"; Model = "qwen-plus"; } else if (p == "Ollama") { Endpoint = "http://localhost:11434/v1/chat/completions"; Model = "qwen2.5-coder:7b"; ApiKey = "ollama"; } }
    void DetectEndpoint() { if (sending || string.IsNullOrEmpty(Endpoint)) return; status = "Testing endpoint..."; var probe = new UnityWebRequest(Endpoint, "POST") { uploadHandler = new UploadHandlerRaw(Encoding.UTF8.GetBytes(JsonUtility.ToJson(new Req { model = Model, messages = new[] { new Msg { role = "user", content = "ping" } } }))), downloadHandler = new DownloadHandlerBuffer(), timeout = 20 }; probe.SetRequestHeader("Content-Type", "application/json"); if (!string.IsNullOrEmpty(ApiKey)) probe.SetRequestHeader("Authorization", "Bearer " + ApiKey); probe.SendWebRequest(); EditorApplication.delayCall += () => { if (!probe.isDone) { EditorApplication.delayCall += () => { }; return; } status = probe.result == UnityWebRequest.Result.Success ? "Endpoint is reachable and returned a compatible response." : "Endpoint check: " + probe.error; probe.Dispose(); Repaint(); }; }
    void Bubble(Msg m) { using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox)) { EditorGUILayout.LabelField(m.role == "user" ? "You" : "Agent", EditorStyles.miniBoldLabel); EditorGUILayout.SelectableLabel(m.content, new GUIStyle(EditorStyles.wordWrappedLabel)); } }
    void InputPanel() { using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox)) { input = EditorGUILayout.TextArea(input, GUILayout.MinHeight(60)); using (new EditorGUILayout.HorizontalScope()) { EditorGUI.BeginDisabledGroup(sending); if (GUILayout.Button("Send (Ctrl+Enter)", GUILayout.Height(26))) Send(); EditorGUI.EndDisabledGroup(); if (GUILayout.Button("Preview context", GUILayout.Width(120))) Debug.Log(BuildContext()); } var e = Event.current; if (e.type == EventType.KeyDown && e.keyCode == KeyCode.Return && (e.control || e.command)) { e.Use(); Send(); } } }
    void PickFile() { var p = EditorUtility.OpenFilePanel("Attach shader or script", Application.dataPath, "shader,compute,hlsl,shadergraph,cs,txt"); if (!string.IsNullOrEmpty(p)) AttachedFile = p; }
    string BuildContext() { var sb = new StringBuilder(); if (IncludeScene) { var s = UnityEngine.SceneManagement.SceneManager.GetActiveScene(); sb.AppendLine("Scene: " + s.name + " (" + s.path + ")"); var rp = GraphicsSettings.currentRenderPipeline; sb.AppendLine("Render pipeline: " + (rp ? rp.GetType().Name : "Built-in")); } if (IncludeSelection && Selection.gameObjects.Length > 0) { sb.AppendLine("Selection:"); foreach (var go in Selection.gameObjects.Take(8)) { sb.AppendLine("- " + go.name); foreach (var r in go.GetComponents<Renderer>().Take(2)) foreach (var mat in r.sharedMaterials.Take(4)) if (mat) sb.AppendLine("  material " + mat.name + ", shader " + (mat.shader ? mat.shader.name : "missing")); } } if (IncludeLogs && logs.Count > 0) { sb.AppendLine("Recent Console:"); foreach (var l in logs.Skip(Math.Max(0, logs.Count - 12))) sb.AppendLine("[" + l.type + "] " + l.text); } if (!string.IsNullOrEmpty(AttachedFile) && File.Exists(AttachedFile)) { var text = File.ReadAllText(AttachedFile); if (text.Length > 30000) text = text.Substring(0, 30000); sb.AppendLine("Attached file: " + AttachedFile); sb.AppendLine("```\n" + text + "\n```"); } return sb.ToString().Trim(); }
    void GrabLog() { try { var p = Application.consoleLogPath; if (!File.Exists(p)) return; foreach (var line in File.ReadAllLines(p).Reverse().Take(3000).Where(x => x.IndexOf("error", StringComparison.OrdinalIgnoreCase) >= 0).Take(20)) if (!logs.Any(x => x.text == line.Trim())) logs.Add(new LogItem { type = "Log", text = line.Trim() }); status = "Imported recent errors."; } catch (Exception e) { status = e.Message; } }
    void CopyPrompt() { var q = input.Trim(); EditorGUIUtility.systemCopyBuffer = q + "\n\n--- Unity context ---\n" + BuildContext(); status = "Prompt copied."; }
    void Send() { if (sending) return; var q = input.Trim(); if (string.IsNullOrEmpty(q)) return; if (string.IsNullOrEmpty(Endpoint) || (Endpoint.StartsWith("http") && string.IsNullOrEmpty(ApiKey) && Provider != "Ollama")) { settings = true; status = "Configure endpoint and API key first."; return; } var ctx = BuildContext(); var user = q + (string.IsNullOrEmpty(ctx) ? "" : "\n\n--- Unity context ---\n" + ctx); history.Add(new Msg { role = "user", content = q }); var msgs = new List<Msg> { new Msg { role = "system", content = SystemPrompt } }; msgs.AddRange(history); msgs[1] = new Msg { role = "user", content = user }; var body = JsonUtility.ToJson(new Req { model = Model, messages = msgs.ToArray() }); input = ""; sending = true; status = "Requesting..."; request = new UnityWebRequest(Endpoint, "POST") { uploadHandler = new UploadHandlerRaw(Encoding.UTF8.GetBytes(body)), downloadHandler = new DownloadHandlerBuffer(), timeout = 180 }; request.SetRequestHeader("Content-Type", "application/json"); if (!string.IsNullOrEmpty(ApiKey)) request.SetRequestHeader("Authorization", "Bearer " + ApiKey); request.SendWebRequest(); }
    void UpdateRequest() { if (request == null || !request.isDone) return; var r = request; request = null; sending = false; if (r.result != UnityWebRequest.Result.Success) { var msg = r.error; try { var eb = JsonUtility.FromJson<ErrorBody>(r.downloadHandler.text); if (eb != null && eb.error != null) msg = eb.error.message; } catch { } status = msg; history.Add(new Msg { role = "assistant", content = "Request failed: " + msg }); } else { try { var x = JsonUtility.FromJson<Resp>(r.downloadHandler.text); var reply = x.choices != null && x.choices.Length > 0 ? x.choices[0].message.content : "Empty response"; history.Add(new Msg { role = "assistant", content = reply }); status = ""; } catch (Exception e) { status = "Parse error: " + e.Message; } } r.Dispose(); Repaint(); }
}


